In [2]:
import zipfile

with zipfile.ZipFile("cbow_s300.zip", "r") as zip_ref:
    zip_ref.extractall("cbow_s300")  # cria a pasta e extrai tudo lá

In [3]:
import pandas as pd
artigo_treino = pd.read_csv("data/treino.csv")
artigo_teste = pd.read_csv("data/teste.csv")
artigo_treino.sample(5)

,title,text,date,category,subcategory,link
27647,Artista tunisiano faz mural gigante em homenag...,"Em Manshiyat Naser, na periferia do Cairo, as ...",2016-03-30,mundo,NaN,http://www1.folha.uol.com.br/mundo/2016/03/175...
993,Marcelo Odebrecht diz que Itaquerão foi 'pepin...,"Em depoimento para a Justiça Eleitoral, o ex-p...",2017-03-23,esporte,NaN,http://www1.folha.uol.com.br/esporte/2017/03/1...
29983,"Osasco rompe tabu, bate Rio e sai na frente em...",O Osasco venceu o Rio de Janeiro por 3 sets a ...,2016-03-21,esporte,NaN,http://www1.folha.uol.com.br/esporte/2016/03/1...
1340,Sonetos de William Shakespeare são musicados p...,Foi a masturbação que levou o músico norte-ame...,2016-05-25,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2016/05...
43153,"Tela de Basquiat vendida por US$ 53,8 milhões ...",Uma das obras mais aguardadas a entrar em leil...,2016-10-05,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2016/05...

In [4]:
artigo_teste.sample(5)

,title,text,date,category,subcategory,link
8828,Bonde turístico em Santos tem veículo inspirad...,A linha de bondes turísticos que percorre o ce...,2016-09-23,cotidiano,NaN,http://www1.folha.uol.com.br/cotidiano/2016/09...
5194,Ponte para o futuro,BRASÍLIA - O Senado ainda não confirmou o impe...,2016-02-08,colunas,bernardomellofranco,http://www1.folha.uol.com.br/colunas/bernardom...
19360,Clube diz que vai advertir ginasta envolvido e...,O Pinheiros vai advertir o ginasta Arthur Nory...,2015-05-18,esporte,NaN,http://www1.folha.uol.com.br/esporte/2015/05/1...
11510,Gol reduz em 10 minutos tempo para fazer check...,A Gol anunciou nesta quinta-feira (17) uma mud...,2016-11-17,mercado,NaN,http://www1.folha.uol.com.br/mercado/2016/11/1...
11299,Governo libera redução de salário e jornada de...,O governo vai permitir que empresas reduzam sa...,2016-12-28,mercado,NaN,http://www1.folha.uol.com.br/mercado/2016/12/1...

In [5]:
artigo_teste.iloc[643].title

'Somos todos imprevisíveis'

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

texto =[
        "tenha um bom dia",
        "tenha um péssimo dia",
        "tenha um ótimo dia",
        "tenha um dia ruim python java alura caelum papa"
    
]

vetorizador = CountVectorizer()
vetorizador.fit(texto)

CountVectorizer()

In [7]:
print(vetorizador.vocabulary_)

{'tenha': 9, 'um': 10, 'bom': 1, 'dia': 3, 'péssimo': 7, 'ótimo': 11, 'ruim': 8, 'python': 6, 'java': 4, 'alura': 0, 'caelum': 2, 'papa': 5}

In [8]:
vetor_bom = vetorizador.transform(["bom"])
print(vetor_bom.toarray())

[[0 1 0 0 0 0 0 0 0 0 0 0]]

In [9]:
vetor_otimo = vetorizador.transform(["ótimo"])
print(vetor_otimo.toarray())

[[0 0 0 0 0 0 0 0 0 0 0 1]]

In [10]:
with open("cbow_s300/cbow_s300.txt") as f:
    for linha in range(10):
        print(next(f))

929606 300

</s> -0.001667 -0.000158 -0.000026 0.001300 -0.000796 0.001527 0.000046 0.000584 0.000449 -0.000100 0.000353 0.001251 0.001069 0.000506 0.000574 0.000838 -0.000930 -0.001220 0.000317 0.001315 -0.001120 0.001373 -0.000040 -0.001580 0.000421 -0.000667 -0.001556 -0.000746 0.001604 0.001157 -0.000027 0.000354 0.000358 -0.000527 -0.000573 -0.001512 -0.001557 -0.001637 0.001617 -0.001511 -0.001022 -0.001426 0.001086 -0.001033 0.000593 0.000724 0.000627 -0.000450 -0.001140 0.000333 0.000524 0.001541 0.000284 0.000617 -0.000807 -0.000088 -0.000364 0.001126 -0.001230 -0.001138 -0.001280 0.001330 0.001257 0.000576 0.000764 0.000684 0.001008 -0.000215 -0.000629 -0.001228 -0.001557 -0.000311 -0.000246 0.000045 0.001136 -0.000645 -0.000549 0.001099 0.000858 -0.000886 0.000553 0.000303 0.001433 0.000732 0.001321 -0.000894 -0.000700 -0.000661 -0.001484 -0.000950 -0.001556 -0.000809 0.000348 -0.000068 0.000724 -0.000569 -0.000161 -0.001628 -0.001437 -0.000259 -0.000296 -0.001571 0.000149 0.000847 0.000613 0.000802 0.001507 0.001015 0.000377 0.000255 -0.000458 -0.000777 -0.001561 0.001601 -0.001520 -0.001210 0.000106 0.000714 0.000392 0.001311 -0.001192 -0.000090 -0.001097 0.000424 -0.000954 -0.001272 -0.001178 0.000036 -0.000181 0.000331 -0.001453 -0.001488 -0.001033 -0.000377 0.000257 -0.001418 0.001109 0.000722 0.000936 -0.000113 0.001215 -0.000263 0.000652 0.001190 -0.000258 0.001391 0.001213 0.000783 -0.001202 0.000470 -0.000879 0.000688 -0.001163 -0.001105 0.001497 0.001304 -0.001322 -0.001501 0.001377 0.001439 0.000884 0.000484 0.001239 -0.001578 0.000981 -0.000318 -0.001180 -0.001375 -0.001491 0.001057 -0.001028 0.000893 0.001028 0.000772 0.001636 -0.000331 -0.000247 -0.001006 -0.000329 0.000837 0.000605 -0.000959 0.001410 0.000488 0.001167 -0.000293 -0.001188 -0.000001 0.001135 0.001141 0.001504 0.000198 -0.001060 0.001551 -0.000003 -0.001474 -0.000391 -0.000880 0.000433 -0.000976 -0.001417 0.000563 -0.001188 0.000593 0.001584 -0.001602 -0.000439 -0.001148 -0.001256 0.001185 -0.000738 0.001543 -0.000846 -0.001029 -0.000641 -0.001587 0.001439 -0.001251 0.000942 -0.001414 -0.001106 0.001087 -0.000027 0.000757 -0.000159 -0.001014 -0.000891 0.000024 -0.000238 0.000157 -0.001067 0.000902 -0.001050 -0.000428 -0.001606 -0.000988 0.001391 0.001165 -0.000113 -0.001000 -0.000055 -0.001369 0.000684 0.000715 0.001407 0.000613 0.001389 0.001315 -0.000130 -0.001044 0.000175 -0.000035 0.000959 -0.000345 0.001209 -0.001251 -0.001219 0.001231 -0.000996 -0.001388 0.001038 0.001336 -0.001066 -0.000881 -0.001066 -0.001466 -0.000274 0.000201 0.000401 0.000132 0.000588 0.000589 -0.000128 0.001073 0.001197 0.000109 0.000770 0.001221 0.000996 -0.001174 0.000135 -0.001134 -0.001385 -0.000311 -0.001631 -0.000564 0.001162 -0.000322 -0.000469 0.001312 -0.001402 0.000239 0.000184 0.001300 0.000021 -0.001065 0.000047 -0.000301 0.001336 0.000332

, -0.061483 -0.094368 -0.008557 -0.034702 0.021108 -0.011873 -0.041133 -0.095925 0.034668 -0.085286 0.076174 0.003314 0.019222 -0.038695 -0.008963 0.053399 0.162935 0.050372 -0.020163 -0.027230 0.061531 0.060840 0.074610 -0.056173 0.007621 -0.055220 0.018008 0.026096 0.033154 -0.082612 -0.081761 0.164978 -0.034423 0.003094 -0.018217 -0.087445 -0.074446 -0.000142 0.004218 0.036585 0.016095 -0.129141 -0.119698 -0.053717 0.005053 -0.114520 -0.017219 0.023693 -0.024115 0.053125 0.024658 -0.037689 0.012078 0.112701 0.028037 0.047618 -0.024196 0.050112 -0.073095 -0.090859 -0.030613 -0.109599 0.037756 0.063827 0.022537 -0.029640 -0.016311 0.021875 0.064882 0.039002 -0.082970 -0.043166 0.013695 -0.043153 -0.082203 -0.020087 -0.100360 0.007033 -0.074208 -0.067789 -0.024897 -0.020358 0.041731 0.101332 0.020217 -0.032473 0.087827 -0.033611 -0.150526 -0.016615 0.021147 -0.025058 0.097833 0.065067 0.051287 -0.079191 0.089563 -0.008436 -0.038352 0.019787 -0.058452 -0.009696 -0.051077 -0.112245 0.024886 -0.015172 -0.129670 0.068672 0.068483 0.009049 0.007055 -0.032763 0.001527 0.054264 0.029924 -0.023482 0.047470 0.008044 0.014534 0.071155 0.016700 -0.027491 -0.155782 0.039370 0.116605 -0.001262 -0.026638 -0.067078 0.078015 -0.066153 -0.039303 0.009535 -0.055698 -0.022250 0.046948 0.053810 0.038096 0.032157 -0.075257 0.008125 -0.034598 -0.020667 -0.003153 0.032491 -0.031064 0.030744 -0.049023 -0.046149 0.000792 0.010385 -0.057119 -0.122554 0.003210 -0.054363 -0.100899 0.069873 -0.009758 0.055455 0.049243 0.008346 -0.016087 0.093572 0.024125 0.058736 0.037243 -0.007478 0.032175 -0.054205 0.008798 0.032326 0.028384 -0.032259 -0.041842 -0.058281 -0.025145 0.011097 0.023598 -0.033376 0.026204 0.032505 -0.009283 0.041076 0.055565 -0.081757 -0.010077 0.058251 -0.014379 -0.040951 0.006938 -0.004179 0.052006 -0.063725 0.035674 -0.066554 0.030910 -0.004032 0.077445 0.029495 -0.064931 0.040263 -0.055423 -0.021571 0.086767 -0.003583 0.073308 -0.043991 0.022503 -0.028692 -0.063626 -0.048238 0.013439 -0.043673 -0.101352 -0.004321 0.125507 0.088486 0.042756 -0.014497 -0.053445 0.021800 0.038406 -0.034023 -0.074428 -0.132825 0.082152 -0.068497 0.004738 0.047527 -0.073890 0.051089 -0.055886 -0.047786 0.040247 -0.053966 -0.015752 0.099451 0.008218 -0.010716 -0.031540 0.036168 0.054244 0.051809 0.035158 0.043006 -0.027902 0.000130 0.103397 -0.114831 -0.036648 -0.036143 0.024432 0.084740 0.001801 0.044475 -0.035746 -0.024109 0.051210 -0.025769 0.016073 -0.000351 -0.029183 -0.075292 0.042163 0.025010 -0.041439 -0.059192 0.026617 -0.040852 0.034697 0.014691 -0.057382 0.046141 0.070360 0.045274 0.065880 0.011023 -0.031292 -0.015784 -0.023421 -0.042788 0.019669 0.035010 0.036188 -0.058060 -0.093562 0.030321 -0.054753 0.097162 0.001134 0.018939 -0.150218 -0.009928 0.051118 0.105212 -0.055051 -0.047959 -0.136800 -0.003198 0.068969 -0.022456

de -0.232068 0.066729 0.103946 -0.072608 0.126237 -0.004782 -0.025139 -0.141489 -0.069438 -0.071078 0.175772 -0.017257 0.094824 0.011020 0.029226 -0.010670 0.144973 0.105333 -0.088273 -0.070952 0.054747 -0.048955 -0.047809 -0.030763 -0.052293 -0.003596 0.078465 0.144430 0.129697 -0.078427 -0.025080 0.212887 0.119806 0.101703 -0.142488 -0.031272 -0.026594 -0.109429 -0.154688 -0.121492 -0.103781 -0.177948 -0.125544 -0.120136 0.031658 0.054160 0.060493 -0.115676 0.132511 -0.001668 -0.125569 -0.124120 0.029025 0.006200 -0.007915 0.058489 0.122710 0.004660 -0.082200 0.123740 0.052747 -0.065657 0.154747 0.155071 0.003547 -0.154675 -0.035110 0.119117 0.080579 0.044262 0.048753 0.054975 -0.064624 -0.046866 0.028242 0.144197 0.029916 -0.024569 0.195781 -0.028608 -0.008233 -0.032542 0.012042 0.011934 -0.068173 0.037028 0.018363 -0.038244 -0.091176 -0.019795 0.051640 -0.008025 -0.025825 -0.001686 -0.069845 -0.039987 0.066244 0.088229 -0.171358 -0.030783 0.082344 0.059267 0.000550 -0.216285 -0.201356 -0.131063 -0.033069 -0.057126 -0.127576 -0.099251 -0.044669 0.035363 -0.119503 -0.090019 -0.006226 -0.000546 0.020731 0.016140 -0.007438 0.032885 -0.161048 0.105681 -0.115705 -0.078013 0.102293 -0.107958 -0.025926 -0.067986 0.017502 -0.054865 -0.007930 -0.006999 -0.000949 -0.026097 0.106295 0.115368 -0.033742 -0.046025 0.009641 -0.065890 0.198822 0.078333 0.062547 0.044947 -0.098424 0.140951 0.109045 -0.004204 -0.174950 0.034234 0.040793 -0.210289 0.104861 0.083616 -0.042511 -0.031439 -0.113108 0.000401 -0.171665 0.097890 0.008065 0.080684 -0.009576 -0.042125 0.177337 -0.005585 -0.004165 0.069755 -0.100323 -0.023289 0.039458 -0.089292 0.069543 -0.009576 0.011562 -0.076654 0.009681 -0.018808 -0.047881 0.026709 -0.021200 -0.032544 0.100362 0.037157 0.005169 -0.001280 -0.064330 -0.049024 -0.002354 0.004443 0.049129 0.026813 0.034249 0.068827 -0.038583 -0.116914 -0.107378 0.046983 0.038218 -0.082186 -0.124208 0.066872 -0.081745 -0.016516 0.016110 0.046844 0.176223 0.083604 -0.086893 -0.114739 -0.159588 0.007700 0.004887 0.006024 -0.020026 0.045816 0.033604 0.054474 0.089348 -0.024353 0.104835 0.084334 0.052662 -0.041422 -0.027877 0.002816 0.150068 -0.052310 0.017154 -0.152326 0.067753 -0.082644 0.119430 -0.012345 0.082965 -0.005791 -0.082770 -0.030068 -0.037331 -0.075347 0.035060 -0.092023 -0.001051 0.012675 0.128757 -0.048579 -0.078527 -0.134126 -0.060009 0.096834 -0.045947 0.132404 -0.030576 -0.006618 -0.088179 -0.124597 -0.095311 -0.086943 0.007010 0.059925 -0.077005 -0.035458 -0.017957 0.081104 0.060141 0.152996 0.083737 -0.025909 0.005420 -0.006300 -0.075839 -0.012399 -0.001624 0.039090 -0.040755 -0.013051 -0.072733 -0.048062 -0.082573 -0.013851 -0.120222 0.011452 -0.083538 0.015996 -0.110800 0.012405 0.045823 0.026705 -0.040789 0.064309 0.007381 -0.037854 0.076050 0.104702 0.010307 -0.103478 0.085227 0.064233 -0.015908 -0.047998

. 0.027867 0.077901 -0.054738 -0.095938 -0.010536 0.015269 -0.005752 -0.048440 -0.104021 0.054583 0.050108 0.054979 0.071112 -0.056665 -0.140868 0.203626 0.211330 0.137270 -0.038069 -0.108607 0.060027 0.052436 0.126758 -0.078212 0.008864 -0.028087 0.029884 0.114899 -0.058657 -0.166441 -0.188866 0.294844 -0.147703 -0.095883 -0.104021 -0.097608 -0.172317 0.035795 -0.019025 0.057503 -0.030564 -0.125182 -0.257359 -0.106566 -0.002708 -0.035769 -0.072053 -0.005640 0.016920 0.155101 -0.226088 -0.070904 -0.110280 -0.075773 -0.190123 0.197397 -0.108603 0.155954 0.096544 -0.183301 0.008154 -0.195997 0.035284 -0.025561 0.159142 -0.141005 0.140643 -0.160588 0.140709 0.059974 -0.012396 -0.074953 -0.038325 -0.165941 -0.226005 -0.043738 0.052905 0.085072 -0.165731 0.016894 -0.136569 0.088165 -0.032044 0.022789 0.051207 0.015907 0.093662 0.037576 -0.286139 -0.107587 0.165001 0.095293 0.181427 0.038072 0.078180 -0.116599 0.138464 0.138386 0.020201 -0.028087 0.038829 -0.040074 -0.044944 -0.179895 0.035044 0.090347 -0.036088 0.154828 0.090421 0.172175 -0.127294 0.060227 0.164694 0.141367 0.049326 -0.136940 0.060633 -0.089581 -0.069639 0.043680 0.141455 -0.060588 -0.118859 0.181506 -0.051302 0.165763 0.151366 -0.191232 -0.103888 -0.077344 -0.016534 0.073607 -0.008464 0.216368 0.038251 0.002552 -0.112613 -0.049596 0.018040 -0.032907 -0.131335 -0.049530 0.057485 0.129446 -0.017884 0.075667 -0.061577 -0.015305 0.007649 0.116636 -0.132568 -0.244250 -0.048748 0.003139 -0.123311 0.018462 0.126955 0.079116 -0.067653 0.019126 0.044182 0.037610 0.199809 -0.118487 0.011276 -0.061652 -0.034426 -0.120148 -0.171490 0.009182 0.182921 -0.165212 0.149898 0.062080 -0.129040 0.051808 -0.075070 -0.068688 0.018707 -0.008050 0.108429 -0.111089 0.021230 -0.125982 0.077740 0.140251 -0.051900 0.036107 0.019580 -0.084050 0.065747 0.015718 -0.016900 -0.026964 0.126565 -0.087491 0.069504 0.108362 -0.006355 0.118521 -0.002510 0.060457 0.082848 0.000294 -0.037938 -0.026097 0.084446 0.015568 -0.050540 -0.117080 0.100227 -0.046050 -0.059615 0.086632 0.097266 0.084578 -0.036891 -0.033246 0.021302 -0.149581 -0.006353 -0.035713 -0.177163 -0.016629 -0.028634 -0.147015 -0.017861 0.009931 -0.181849 0.065564 -0.007616 0.094861 0.089787 0.005743 -0.127185 0.093027 -0.107247 -0.019161 -0.201082 -0.008504 0.126500 0.034318 0.011876 0.012696 -0.090981 0.012814 0.038388 -0.274763 -0.123303 -0.073078 0.027702 0.035841 -0.080954 0.091305 0.029009 -0.006000 0.121087 0.016678 -0.070181 -0.080839 -0.016332 -0.081390 -0.059594 0.131390 0.039603 -0.222503 -0.039382 -0.071041 0.267399 -0.010011 -0.077326 -0.044107 0.052901 0.023623 -0.087243 0.011539 -0.006381 -0.074194 -0.041591 -0.061872 -0.098552 -0.094357 -0.062879 -0.150341 -0.087596 0.330078 0.028435 0.087784 0.034434 -0.008122 -0.258485 -0.109828 0.013279 0.043340 0.136803 -0.081573 -0.136733 -0.081884 0.306241 0.093106

a -0.019764 -0.096043 -0.010960 0.102012 -0.101848 -0.010257 0.004692 -0.165735 -0.179723 0.067659 0.037108 0.100931 -0.211779 0.163603 -0.042376 -0.021683 -0.014900 0.101581 -0.053583 0.065435 0.126251 0.062320 -0.057445 -0.107130 -0.037044 -0.072958 -0.066655 -0.067962 -0.070879 -0.187941 0.065208 0.102302 -0.024876 0.151433 0.012228 -0.065570 -0.063793 0.015519 0.046230 0.174824 -0.100376 -0.081244 -0.039337 0.017851 0.125168 -0.096404 -0.133070 -0.023451 0.117965 0.005949 0.038928 0.060488 -0.014678 0.024891 -0.001455 0.048539 0.133535 0.084564 0.018362 -0.054294 -0.235691 -0.151528 0.043101 -0.097685 -0.034775 -0.127507 0.010346 -0.010458 0.047631 0.002045 -0.013826 -0.139644 0.128220 -0.020997 -0.057176 0.007458 -0.033133 -0.083235 -0.075585 -0.079414 -0.023531 0.076794 0.051968 0.026857 0.007574 -0.039602 0.027458 -0.146083 0.008662 0.113647 0.007963 0.023413 0.088046 -0.079530 0.027995 -0.017113 -0.056750 0.069447 0.094213 0.123728 0.010051 -0.054795 0.041003 -0.044294 -0.066911 -0.025221 0.059618 0.023494 -0.095354 0.029266 0.047979 0.079102 -0.061757 0.116363 0.011112 0.136784 -0.027020 -0.002793 -0.092629 -0.047217 0.111263 0.102819 0.090932 -0.085343 -0.026490 -0.033315 -0.028970 -0.118673 -0.067360 -0.207183 -0.076011 0.017469 -0.078908 0.031023 0.090820 -0.054443 0.062466 0.065952 -0.028265 0.051329 0.090671 0.106923 0.028011 0.014720 -0.036025 0.099207 -0.013510 -0.147551 -0.077657 -0.099269 0.001171 0.059405 -0.006946 0.123997 0.023131 0.102308 -0.040784 0.027455 -0.181898 0.095958 0.155467 -0.077250 -0.124941 0.058529 0.035851 -0.004447 0.035127 -0.024015 -0.029101 -0.107558 0.055650 -0.017027 0.008997 -0.016504 0.018768 -0.080671 0.029003 0.013937 0.002876 -0.064262 0.001246 0.073494 -0.013986 -0.100303 0.027376 0.030375 -0.177618 0.016413 -0.008711 -0.257308 -0.031904 0.068326 0.038748 0.006762 -0.045245 0.038158 0.093055 -0.069432 -0.140442 -0.030486 -0.097529 0.251017 -0.059000 -0.037363 -0.020030 0.116937 0.018191 -0.005464 0.016485 0.009930 0.007318 -0.131821 -0.005316 -0.063905 0.066936 -0.007235 0.066709 0.153262 -0.087015 -0.196866 0.042973 0.124447 0.034619 -0.021113 0.029881 -0.072679 0.068707 -0.033823 -0.140311 -0.158137 0.215081 -0.020170 -0.062018 -0.038955 0.158768 -0.155656 0.016471 -0.071324 0.069629 -0.070692 0.114725 0.114054 0.154133 -0.143244 -0.082015 -0.070578 0.094558 -0.073491 -0.084676 0.089027 -0.053428 0.034783 0.007488 0.008849 0.137206 -0.061942 -0.155206 -0.022297 -0.054165 0.206418 0.058566 0.033847 0.039555 0.042072 -0.003160 0.350700 -0.067416 -0.089351 0.147734 0.026404 -0.128322 -0.143885 -0.189820 0.162824 -0.038651 -0.045660 0.083507 0.118510 -0.054740 -0.053446 -0.106545 -0.087144 -0.159905 0.006153 0.057539 0.079486 -0.015659 -0.014220 -0.013549 -0.122177 -0.154875 0.319072 -0.251233 0.070468 -0.084041 -0.067580 -0.163386 -0.026553 -0.033245 -0.035199

o 0.050016 0.094213 -0.234393 0.057870 -0.255710 -0.099076 0.162541 -0.073166 -0.072231 0.087253 0.154162 -0.021438 0.095246 0.086680 0.027481 0.055959 0.176635 -0.158901 -0.076106 -0.036695 0.115689 -0.039255 -0.116532 -0.143528 0.059030 0.049429 -0.009721 0.204578 -0.020946 -0.254149 -0.167956 0.024087 -0.094412 -0.066287 -0.085987 -0.081115 -0.035314 -0.000736 0.069831 -0.034319 -0.041741 0.007945 0.106777 0.119971 -0.051358 0.152951 -0.109669 0.102599 0.102598 0.044424 -0.088313 0.142374 0.042868 -0.042467 0.199348 -0.234265 -0.044845 -0.109492 0.005783 -0.045873 -0.049017 -0.037446 0.105329 -0.163747 -0.139140 0.153179 -0.117726 -0.113436 0.010813 0.097110 0.074618 0.041083 0.082912 -0.052041 0.009895 0.160828 0.058190 -0.215907 -0.024543 0.042466 -0.011712 0.064930 0.097498 -0.080108 0.019837 -0.059179 0.077248 -0.135312 0.132748 0.069083 0.075949 -0.232743 0.078279 -0.078944 0.116486 0.004099 0.057786 -0.125938 0.068976 0.176170 0.044454 0.085901 0.033849 0.057793 -0.083662 0.061258 -0.037814 0.050392 -0.067302 -0.102103 -0.011153 0.029286 0.032976 0.003400 0.061664 0.076337 -0.097293 0.026432 -0.059397 -0.160978 0.069399 0.307550 0.069981 -0.122410 0.003086 0.027841 0.134213 -0.018279 -0.025608 -0.156602 0.062460 -0.051757 0.030337 -0.042270 0.007516 0.055478 0.075345 0.112685 -0.047181 0.001009 0.031433 -0.134699 -0.034702 -0.082685 -0.182748 -0.097813 0.053774 -0.067876 -0.090774 -0.035145 0.080364 -0.242563 0.024905 -0.012293 0.110051 0.103592 0.138403 -0.035121 0.037955 -0.028042 0.005687 0.042462 0.045434 0.127590 -0.049950 0.079609 -0.152268 -0.102837 -0.083840 -0.132681 -0.073176 0.031672 0.104991 0.082840 0.142188 -0.047643 0.054661 -0.112325 0.006551 0.079335 0.011705 -0.042121 0.086597 0.088994 0.079949 -0.002677 0.106816 -0.055035 0.068153 -0.167192 0.009149 -0.028594 -0.039560 0.001607 -0.122615 0.106024 0.107250 0.050540 -0.043291 0.061397 0.001380 0.054964 0.040893 -0.045046 0.002312 0.032035 -0.026698 -0.042064 0.144622 0.076241 0.024255 -0.086833 0.098275 -0.083894 0.086363 -0.004560 -0.029056 0.126784 0.071785 -0.025692 0.000966 0.100620 0.030299 -0.163968 0.042070 -0.198341 0.099603 -0.113758 0.124685 -0.069966 -0.165131 -0.134782 -0.020419 -0.112747 0.123515 -0.045274 0.167949 -0.109681 -0.146224 0.075453 0.054352 0.023153 -0.062161 -0.059457 -0.124327 0.041855 0.205124 -0.083616 -0.062827 0.017066 0.025000 0.079311 0.018874 -0.055492 -0.129246 0.099183 -0.022749 -0.079510 -0.130005 0.012160 0.060842 0.018816 -0.180103 0.057191 0.018971 0.216519 -0.003726 0.155861 0.112271 0.091379 -0.073707 -0.059254 0.011068 -0.005690 -0.098677 -0.082454 0.105838 0.042144 0.100894 0.096960 -0.228625 0.064737 0.022971 -0.001549 -0.105277 0.149519 -0.055187 0.201671 0.098550 0.056229 -0.107189 -0.005223 -0.077126 0.020865 -0.098107 0.064205 -0.174567 0.196321 0.233813 0.038634


In [ ]:
from gensim.models import KeyedVectors

modelo = KeyedVectors.load_word2vec_format("cbow_s300/cbow_s300.txt")

In [0]:
modelo.most_similar("china")

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('rússia', 0.7320704460144043),
 ('índia', 0.7241617441177368),
 ('tailândia', 0.701935887336731),
 ('indonésia', 0.6860769987106323),
 ('turquia', 0.6741335988044739),
 ('malásia', 0.6665689945220947),
 ('mongólia', 0.6593616008758545),
 ('manchúria', 0.6581847667694092),
 ('urss', 0.6581669449806213),
 ('grã-bretanha', 0.6568098068237305)]

In [0]:
modelo.most_similar("itália")

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('frança', 0.7983609437942505),
 ('grécia', 0.7547340989112854),
 ('espanha', 0.7417078018188477),
 ('holanda', 0.7343162298202515),
 ('grã-bretanha', 0.7281740307807922),
 ('inglaterra', 0.7172061204910278),
 ('bélgica', 0.7155542373657227),
 ('alemanha', 0.7135661840438843),
 ('suécia', 0.6831519603729248),
 ('áustria', 0.6822685599327087)]

In [0]:
modelo.most_similar(positive=["brasil", "argentina"])

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('chile', 0.6781662702560425),
 ('peru', 0.6348033547401428),
 ('venezuela', 0.6273865103721619),
 ('equador', 0.6037014722824097),
 ('bolívia', 0.6017140746116638),
 ('haiti', 0.5993807315826416),
 ('méxico', 0.5962306261062622),
 ('paraguai', 0.5957703590393066),
 ('uruguai', 0.5903672575950623),
 ('japão', 0.5893509984016418)]

In [0]:
#nuvens -> nuvem : estrelas -> estrela
#nuvens + estrela - nuvem = estrelas

modelo.most_similar(positive=["nuvens", "estrela"], negative=["nuvem"])

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('estrelas', 0.5497429966926575),
 ('plêiades', 0.379197895526886),
 ('colinas', 0.3746805191040039),
 ('trovoadas', 0.373703271150589),
 ('sombras', 0.3734194040298462),
 ('pombas', 0.3726757764816284),
 ('corredoras', 0.3640727698802948),
 ('cigarras', 0.36065393686294556),
 ('galáxias', 0.35754913091659546),
 ('luas', 0.3575345277786255)]

In [0]:
modelo.most_similar(positive=["professor", "mulher"], negative=["homem"])

/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):

[('professora', 0.6192208528518677),
 ('aluna', 0.5449554324150085),
 ('esposa', 0.4978231191635132),
 ('ex-aluna', 0.4884248375892639),
 ('namorada', 0.4737858772277832),
 ('enfermeira', 0.4728144109249115),
 ('filha', 0.467373788356781),
 ('irmã', 0.45845913887023926),
 ('ex-namorada', 0.45824766159057617),
 ('ex-professora', 0.4510470926761627)]

## Vetorização de texto

In [0]:
artigo_treino.title.loc[12]

"Daniel Craig será stormtrooper em novo 'Star Wars', diz ator"

In [0]:
import string
import nltk
nltk.download('punkt')

def tokenizador(texto):
    texto = texto.lower()
    lista_alfanumerico = []

    for token_valido in nltk.word_tokenize(texto):
        if token_valido in string.punctuation: continue
        lista_alfanumerico.append(token_valido)

    return lista_alfanumerico

tokenizador("Texto Exemplo, 1234.")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

['texto', 'exemplo', '1234']

In [0]:
import numpy as np
def combinacao_de_vetores_por_soma(palavras_numeros):
    vetor_resultante = np.zeros(300)
    for pn in palavras_numeros:
        try:
            vetor_resultante += modelo.get_vector(pn)

        except KeyError:
            if pn.isnumeric():
                pn = "0"*len(pn)
                vetor_resultante += modelo.get_vector(pn)
                
            else:
                vetor_resultante += modelo.get_vector("unknown")
                

    return vetor_resultante

In [0]:
palavras_numeros = tokenizador("texto exemplo caelumx")
vetor_texto = combinacao_de_vetores_por_soma(palavras_numeros)
print(len(vetor_texto))
print(vetor_texto)

300
[ 5.22882011e-01  3.62993002e-01 -1.71584003e-01  7.53853999e-01
 -4.31845989e-01 -1.24049995e-01  5.74063979e-01  1.77530989e-01
 -2.06351001e-01 -3.01645996e-01  1.61487002e-01  2.31922999e-01
 -4.56399992e-01  5.50001010e-01 -1.32122993e-01  1.92305006e-01
 -1.36758396e+00  4.63750064e-02 -2.97930993e-01 -3.18355992e-01
 -6.56941980e-01 -3.62310998e-01  5.73180020e-02  6.63353994e-01
 -1.80777013e-01 -3.66457999e-01 -6.71911031e-01 -2.15881996e-01
  1.83916006e-01  2.27340087e-02 -1.64336992e-01 -3.92086998e-01
  8.35490003e-02 -1.06699858e-03  5.03399931e-02  3.36998001e-01
  4.61871006e-01  4.27312993e-01  1.19738005e-01  1.33754000e-01
 -1.59788008e-01  2.31531011e-01  2.51459002e-01  3.99739010e-01
  2.48164987e-01  1.56523993e-01  4.29660002e-01  5.93577012e-01
  2.75056003e-01  3.36633004e-01 -3.72660076e-02  2.38436002e-01
  1.37460992e-01  9.23399962e-02  2.53910050e-02 -1.70530001e-01
  2.79463995e-01  5.26985995e-01 -3.52820985e-01 -1.45661000e-01
  4.39329892e-02  5.91176983e-01  3.05415988e-01 -4.60560006e-01
  1.64116994e-01  1.74349956e-02  3.33568990e-01 -6.25250079e-02
  1.36688992e-01 -3.35132007e-01  1.52297001e-01 -5.91567017e-01
  1.42685996e-01 -3.98919880e-02 -2.24829994e-01  4.99610007e-02
 -4.03076008e-01 -2.09798999e-01  1.12914998e-01 -2.46080030e-02
 -5.27866997e-01 -2.58233994e-01  3.98681998e-01 -3.34687993e-01
 -1.50378998e-01 -3.87391001e-01 -6.42380990e-01  2.71307994e-01
  3.50582004e-01 -2.71704987e-01 -5.62479943e-02  1.42173000e-01
 -1.88863993e-01  2.13491008e-01  1.45643994e-01  1.71520011e-02
  1.66199356e-03  1.59836000e-01  1.11572002e-01 -5.03702998e-01
  5.62270992e-01 -2.95340006e-01  2.18798996e-01 -3.18340994e-01
 -5.05501201e-03  1.10062998e-01 -6.99969977e-02  1.05841003e-01
 -1.75035000e-01  1.49463996e-01 -9.98530015e-02  1.55179997e-01
  3.90345987e-01 -2.04510996e-01  2.16732007e-01  8.20598751e-03
 -3.61071974e-01 -3.04708008e-01  3.09060000e-01 -5.04589975e-01
  2.35520996e-01 -4.54535998e-01  7.93730021e-02 -4.17084986e-01
 -8.21750015e-02 -6.19894013e-01 -4.11118999e-01  1.88023998e-01
 -4.02039997e-01  2.63135992e-01 -8.87499750e-03 -2.76730135e-02
 -6.48449971e-02  2.38201998e-01  4.98423994e-01 -4.88622014e-01
  2.16963999e-01  1.36010006e-01  5.89024995e-01  2.27308989e-01
 -2.20899995e-01  3.89464989e-01  2.73847998e-01  5.77668022e-01
  9.59669948e-02  6.76499978e-02 -1.65553994e-01 -2.90004537e-04
  7.88033009e-01 -2.69181999e-01 -6.14109933e-02  5.30955017e-01
 -2.40886986e-01 -1.13845013e-01 -2.31698006e-01 -1.02866001e-01
  2.86710015e-01  1.69443004e-01  1.52222987e-01  1.19775005e-01
  8.52080025e-02  3.07620000e-01 -6.64869994e-02 -2.28320003e-01
 -2.54676010e-01  2.92331994e-01  3.20232995e-01  2.67992996e-01
 -1.58863999e-01  1.64530003e-01 -2.07599998e-01 -1.05049998e-01
  4.17909997e-02 -1.75650998e-01 -4.43150014e-01 -2.90811997e-01
  7.69861981e-01 -1.10406995e-01 -5.42975988e-01 -5.79534002e-01
 -4.27169999e-01 -1.23019993e-01 -4.86927018e-01 -3.08948014e-01
  1.51400022e-01 -1.05756983e-01  5.22011004e-01 -1.87405996e-01
 -8.70940000e-01  3.67364988e-01 -1.25985995e-01 -2.49116996e-01
 -4.59964998e-01  4.04862009e-01  1.42723005e-01  8.49129006e-01
 -1.57346986e-01 -3.77651986e-01  3.47406007e-01 -1.46147996e-01
 -3.87908012e-01  2.12949915e-02  2.58639976e-02  5.20209996e-02
 -3.31409002e-01 -8.46849903e-02 -2.99407993e-01 -6.26317017e-01
  3.84700969e-01  8.69952962e-01  9.93819982e-02  1.99093003e-01
  6.33829013e-01  7.57490013e-02  9.95739987e-02 -3.15298987e-01
  3.37154992e-01 -1.65155007e-01 -5.46141015e-01 -4.41580020e-02
 -4.37382001e-01  9.29019973e-02 -1.19208004e-01  5.59970066e-02
  4.88128005e-01  3.34870145e-02 -4.06545982e-01  8.58969986e-02
  1.56048000e-01 -3.18444006e-01  5.76119870e-02 -8.89250003e-02
  3.00845001e-01  8.60029981e-02 -1.12561002e-01 -2.59451986e-01
 -4.27574001e-01  5.16070015e-01 -2.08964005e-01 -4.01911002e-01
  2.16379996e-01  5.28540015e-02  2.69744997e-01 -2.56099971e-03
  7.16881998e-01  1.60955001e-01  8.45750067e-02 -1.10597998e-01
  3.33345998e-01 -2.10211009e-01 -7.19559926e-02  2.72592999e-01
  1.57532996e-01  2.91150147e-02  1.05120018e-02  6.79676987e-01
  2.62389010e-01  6.84430003e-02  6.68206982e-01 -6.26858003e-01
  5.84650040e-02  8.82799178e-03  3.38804010e-01 -2.99689919e-02
 -1.19239949e-02 -5.58409996e-01  3.21900997e-01  4.64350032e-02
  2.20100991e-01 -2.70584986e-01 -1.24694987e-01 -3.76585007e-01
  5.00658989e-01  2.65680000e-01 -5.11230044e-02  4.75329980e-02
  3.36938001e-01  3.25174997e-01  3.22709002e-01 -1.42265998e-01
 -4.42880094e-02 -7.92279951e-02  1.68996006e-01 -6.64460119e-02
  4.03894000e-01 -1.96734998e-01  5.44488981e-01 -6.83254004e-01
 -1.09876001e+00 -4.09158990e-01  6.03299983e-01  3.19462006e-01
 -2.89287008e-01 -4.00324974e-01  5.90330064e-02  6.70336999e-01
  3.17797020e-01 -1.67324007e-01 -6.55779988e-02  1.14503302e+00]

In [0]:
def matriz_vetores(textos):
    x = len(textos)
    y = 300
    matriz = np.zeros((x,y))

    for i in range(x):
        palavras_numeros = tokenizador(textos.iloc[i])
        matriz[i] = combinacao_de_vetores_por_soma(palavras_numeros)

    return matriz

matriz_vetores_treino = matriz_vetores(artigo_treino.title)
matriz_vetores_teste = matriz_vetores(artigo_teste.title)
print(matriz_vetores_treino.shape)
print(matriz_vetores_teste.shape)

(90000, 300)
(20513, 300)

In [0]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(max_iter = 200)
LR.fit(matriz_vetores_treino, artigo_treino.category)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=200,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
LR.score(matriz_vetores_teste, artigo_teste.category)

0.7964705308828548

In [0]:
artigo_teste.category.unique()

array(['colunas', 'esporte', 'mercado', 'cotidiano', 'mundo', 'ilustrada'],
      dtype=object)

In [0]:
from sklearn.metrics import classification_report

label_prevista = LR.predict(matriz_vetores_teste)
CR = classification_report(artigo_teste.category, label_prevista)
print(CR)

              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.93      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513

In [0]:
from sklearn.dummy import DummyClassifier

DC = DummyClassifier()
DC.fit(matriz_vetores_treino, artigo_treino.category)
label_prevista_dc = DC.predict(matriz_vetores_teste)

CR_dummy = classification_report(artigo_teste.category, label_prevista_dc)
print(CR_dummy)

/usr/local/lib/python3.6/dist-packages/sklearn/dummy.py:132: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  "stratified to prior in 0.24.", FutureWarning)

              precision    recall  f1-score   support

     colunas       0.30      0.17      0.22      6103
   cotidiano       0.08      0.16      0.11      1698
     esporte       0.22      0.16      0.19      4663
   ilustrada       0.01      0.22      0.02       131
     mercado       0.28      0.17      0.21      5867
       mundo       0.10      0.17      0.13      2051

    accuracy                           0.17     20513
   macro avg       0.17      0.18      0.14     20513
weighted avg       0.24      0.17      0.19     20513

In [0]:
with zipfile.ZipFile("skip_s300.zip", "r") as zip_ref:
    zip_ref.extractall("skip_s300")  # cria a pasta e extrai tudo lá

Archive:  /content/drive/My Drive/curso_word2vec/skip_s300.zip
  inflating: skip_s300.txt

In [0]:
modelo_skipgram = KeyedVectors.load_word2vec_format("skip_s300/skip_s300.txt")

def combinacao_de_vetores_por_soma_skipgram(palavras_numeros):
    vetor_resultante = np.zeros(300)
    for pn in palavras_numeros:
        try:
            vetor_resultante += modelo_skipgram.get_vector(pn)

        except KeyError:
            if pn.isnumeric():
                pn = "0"*len(pn)
                vetor_resultante += modelo_skipgram.get_vector(pn)
                
            else:
                vetor_resultante += modelo_skipgram.get_vector("unknown")
                

    return vetor_resultante


def matriz_vetores_skipgram(textos):
    x = len(textos)
    y = 300
    matriz = np.zeros((x,y))

    for i in range(x):
        palavras_numeros = tokenizador(textos.iloc[i])
        matriz[i] = combinacao_de_vetores_por_soma_skipgram(palavras_numeros)

    return matriz

matriz_vetores_treino_skipgram = matriz_vetores_skipgram(artigo_treino.title)
matriz_vetores_teste_skipgram = matriz_vetores_skipgram(artigo_teste.title)

#Previsão
LR_skipgram = LogisticRegression(max_iter = 1000)
LR_skipgram.fit(matriz_vetores_treino_skipgram, artigo_treino.category)
label_previsao_skipgram = LR_skipgram.predict(matriz_vetores_teste_skipgram)
CR_skipgram = classification_report(artigo_teste.category, label_previsao_skipgram)
print(CR_skipgram)

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:402: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL

              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.63      0.81      0.70      1698
     esporte       0.93      0.89      0.91      4663
   ilustrada       0.15      0.92      0.26       131
     mercado       0.84      0.82      0.83      5867
       mundo       0.76      0.86      0.81      2051

    accuracy                           0.81     20513
   macro avg       0.69      0.83      0.71     20513
weighted avg       0.84      0.81      0.82     20513

In [0]:
print(CR)

              precision    recall  f1-score   support

     colunas       0.86      0.72      0.78      6103
   cotidiano       0.61      0.79      0.69      1698
     esporte       0.93      0.88      0.90      4663
   ilustrada       0.13      0.88      0.23       131
     mercado       0.84      0.79      0.81      5867
       mundo       0.74      0.86      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.68      0.82      0.70     20513
weighted avg       0.83      0.80      0.81     20513

In [ ]:
import spacy
import numpy as np
import pandas as pd
from gensim.models import KeyedVectors

w2v_modelo_cbow = KeyedVectors.load_word2vec_format("data/modelo_cbow.txt")
w2v_modelo_sg = KeyedVectors.load_word2vec_format("data/modelo_skipgram.txt")
artigo_treino = pd.read_csv("data/treino.csv")
artigo_teste = pd.read_csv("data/teste.csv")

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:253: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL

In [ ]:
nlp = spacy.load("pt_core_news_sm", disable=["paser", "ner", "tagger", "textcat"])

def tokenizador(texto):
    
    doc = nlp(texto)
    tokens_validos = []
    for token in doc:
        e_valido = not token.is_stop and token.is_alpha
        if e_valido:
            tokens_validos.append(token.text.lower())

    
    return  tokens_validos

texto = "Rio de Janeiro 1231231 ***** @#$ é uma cidade maravilhosa!"
tokens = tokenizador(texto)
print(tokens)

['rio', 'janeiro', 'cidade', 'maravilhosa']

In [ ]:
def combinacao_de_vetores_por_soma(palavras, modelo):

    vetor_resultante = np.zeros((1,300))

    for pn in palavras:
        try:
            vetor_resultante += modelo.get_vector(pn)

        except KeyError:
            pass
                

    return vetor_resultante

vetor_texto = combinacao_de_vetores_por_soma(tokens, w2v_modelo_cbow)
print(vetor_texto.shape)
print(vetor_texto)

(1, 300)
[[ 1.98463321e-01  6.81657493e-02  1.46854076e+00 -3.64254490e-01
   1.43774167e-01  8.67518850e-01  5.45219969e-01  1.10110116e+00
  -6.50840998e-01 -3.40783868e+00  1.01653042e+00  1.33011723e+00
   2.09624138e+00 -1.38510185e+00  1.47641352e+00  1.86899729e+00
  -1.59593132e+00  3.16831052e-01 -9.20437280e-01 -6.29614353e-01
   7.00041652e-02 -1.95808137e+00  7.94665724e-01 -7.24693198e-01
   1.39489579e+00  1.73469097e+00  1.26399602e+00 -1.10639864e+00
  -1.78198762e+00 -3.93549776e+00  2.81366953e+00 -2.87773656e-02
  -2.41185263e-01  2.14455798e-01  9.56606358e-01  1.02985160e+00
   1.33243561e+00  3.73910588e+00 -3.42612457e+00  2.09202743e+00
   2.08773389e+00  6.37439638e-01 -1.93942163e-01 -1.25078782e+00
  -1.34374684e+00  5.62602848e-01 -2.27634996e+00 -1.38811620e+00
   8.86206836e-01 -1.02591036e+00 -9.22529399e-01 -8.44487831e-01
   1.45723258e+00  6.67459078e-01  3.34969163e-01  9.08002794e-01
  -2.67864984e+00 -3.10524291e+00 -2.00997367e+00  3.95785213e-01
  -1.44439277e+00 -2.51032397e-01 -4.45651762e-01 -4.12870246e+00
   8.90532818e-01 -2.01850063e+00  2.95132813e+00 -1.63505590e+00
   9.72207695e-01  2.13555911e+00  2.66578168e-01  9.44992900e-01
   1.32113317e+00  2.04084900e+00 -6.31301859e-02 -1.96614408e+00
   3.37847590e-01 -1.42520127e+00 -6.70336679e-01 -2.11732349e+00
   1.25186447e+00  1.68659431e+00  2.66411901e-01 -1.36801040e+00
  -7.10758269e-02  2.59357110e-01  1.35773395e+00 -1.19595477e+00
   3.53217840e-01 -9.13123883e-01 -1.31754772e+00 -1.18083102e+00
  -1.60925594e+00  3.04497349e+00 -8.72487605e-01 -2.93044001e-03
  -4.54608804e-01  4.46252763e-01  1.28295647e+00 -2.14980584e+00
  -1.38042204e-01  2.46452904e+00  5.66329088e-01 -3.96781638e-01
  -1.23308067e+00  9.97751549e-01 -1.18590638e+00 -2.74670758e+00
  -7.14877024e-02 -1.80906725e+00 -2.86876589e-01  1.17532640e+00
   4.07069802e-01 -1.18419093e+00  6.93305757e-01 -2.79858029e+00
   4.96671587e-01  3.88392419e-01 -4.09445107e-01 -1.69088084e+00
  -1.14192608e+00  7.89269388e-01 -1.78837532e+00  3.12441923e-01
   6.15936384e-01 -9.91583828e-01 -8.81297372e-01 -1.59514508e+00
  -3.38194042e-01  2.77336282e+00  1.12952733e+00  6.69487022e-01
  -2.23740930e+00  8.20634864e-01 -1.06027731e+00 -2.66822523e+00
  -6.32109344e-02 -1.37821612e+00 -1.17251796e+00 -3.55709307e-01
  -6.62426069e-01 -6.71470022e-01 -1.30925279e+00  4.03758295e-01
   2.02564555e+00  1.12515477e+00 -7.28528088e-01 -7.24116253e-01
  -7.51860611e-01 -1.38165611e+00 -7.10942745e-01  6.62908029e-01
   1.17665827e+00 -4.10100482e-01 -1.48235688e+00 -2.04781182e-01
  -1.23201726e+00  1.08064251e+00 -1.18060405e+00  2.68656611e-01
   1.26690385e+00  2.07529679e+00 -4.95851181e-01  2.12786660e+00
  -4.10504162e-01 -1.03434661e-01  1.00728732e+00 -1.17085938e+00
   7.91757107e-01  2.06468908e+00 -9.36222613e-01 -8.09373602e-01
  -1.38570577e+00  2.13664442e+00  2.33163209e-01  1.47312683e+00
   8.24551042e-01  2.29994901e+00 -6.97336387e-01  6.98023049e-01
   2.52935290e-01 -1.18311670e+00 -3.79771441e-01  4.99876723e-01
   3.79301339e-01 -2.19207451e-01  1.66882064e+00 -6.41706962e-01
  -2.13766876e+00  7.44811505e-01 -3.76184583e-01 -2.09537953e+00
   3.53986967e+00  1.52019766e+00  8.83280393e-01  2.09651017e+00
   7.47494064e-02 -5.92749387e-01  5.30278683e-01  5.17430790e-01
   1.05905410e-01  1.57121648e+00 -7.50485867e-01 -6.99034393e-01
   1.92299291e-01 -1.27268235e-01  5.42483386e-01  5.62549770e-01
   8.74887835e-01 -1.10270411e+00  1.92472655e+00  4.84076954e-01
   4.90025664e-01  8.58439088e-01  1.54760518e+00 -2.28136891e+00
  -1.18459088e+00  1.09139114e+00  1.43678635e-01  9.29474797e-01
  -1.56311296e+00  2.50907300e+00  5.98837972e-01  2.32589990e-02
  -1.10612132e+00 -1.24443305e+00  3.99853408e-01 -1.93480998e-01
   9.00986910e-01 -6.75875485e-01  1.94404826e-01 -7.21047997e-01
   1.91384749e+00 -3.15805918e+00  1.01168230e-02 -5.83662808e-01
  -1.31580937e+00 -2.20993680e+00 -9.91954342e-01  8.66983831e-01
  -2.31047937e+00 -7.64117956e-01  1.18558701e+00 -1.46488771e+00
  -3.23397577e-01  2.19223410e-01  8.51200102e-01 -1.42025486e-01
  -3.46244995e-01 -1.50617509e+00 -5.46980679e-01 -1.28510725e+00
  -3.88785839e-01  1.15616289e+00 -2.34872121e-01 -1.50918727e+00
  -2.26066348e+00  4.65306818e-01 -2.48372585e-01  9.92207192e-01
   1.38190567e-01 -1.41022006e+00 -2.82525501e+00  6.87229935e-01
   9.62689796e-01 -3.25991720e-01  3.15196460e+00  4.55391541e-01
   9.17801008e-01  9.43651915e-01 -7.63600901e-01  8.58660602e-01
   1.29233295e+00 -4.67246175e-02  3.51564065e-01  2.21975364e-01
  -8.75412375e-02  1.73005044e-01 -1.27859987e+00 -2.57941461e+00
  -2.04670718e+00 -9.41399142e-01 -2.75735289e-01  1.37583555e+00
   2.37762845e+00  4.69325930e-01  5.68931026e-01  3.31017710e-01
  -2.77776279e+00 -1.78476749e+00  2.09891133e-01 -4.68507094e-01
  -8.44822943e-01  1.59221818e+00 -7.10642338e-03 -3.36731445e-01
  -7.84925498e-01 -1.30478811e+00 -8.93859327e-01  1.92370141e+00]]

In [ ]:
def matriz_vetores(textos, modelo):
    x = len(textos)
    y = 300
    matriz = np.zeros((x,y))

    for i in range(x):
        palavras = tokenizador(textos.iloc[i])
        matriz[i] = combinacao_de_vetores_por_soma(palavras, modelo)

    return matriz

matriz_vetores_treino_cbow = matriz_vetores(artigo_treino.title, w2v_modelo_cbow)
matriz_vetores_teste_cbow = matriz_vetores(artigo_teste.title, w2v_modelo_cbow)
print(matriz_vetores_treino_cbow.shape)
print(matriz_vetores_teste_cbow.shape)

(90000, 300)
(20513, 300)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

def classificador(modelo, x_treino, y_treino, x_teste, y_teste):

    RL = LogisticRegression(max_iter = 800)
    RL.fit(x_treino, y_treino)
    categorias = RL.predict(x_teste)
    resultados = classification_report(y_teste, categorias)
    print(resultados)
    
    return RL

RL_cbow = classificador(w2v_modelo_cbow,
                        matriz_vetores_treino_cbow,
                        artigo_treino.category,
                        matriz_vetores_teste_cbow,
                        artigo_teste.category)

              precision    recall  f1-score   support

     colunas       0.81      0.71      0.76      6103
   cotidiano       0.63      0.81      0.71      1698
     esporte       0.93      0.86      0.89      4663
   ilustrada       0.13      0.86      0.23       131
     mercado       0.84      0.78      0.81      5867
       mundo       0.74      0.84      0.79      2051

    accuracy                           0.79     20513
   macro avg       0.68      0.81      0.70     20513
weighted avg       0.82      0.79      0.80     20513

In [ ]:
matriz_vetores_treino_sg = matriz_vetores(artigo_treino.title, w2v_modelo_sg)
matriz_vetores_teste_sg = matriz_vetores(artigo_teste.title, w2v_modelo_sg)

RL_sg = classificador(w2v_modelo_sg,
                        matriz_vetores_treino_sg,
                        artigo_treino.category,
                        matriz_vetores_teste_sg,
                        artigo_teste.category)

              precision    recall  f1-score   support

     colunas       0.81      0.72      0.76      6103
   cotidiano       0.64      0.81      0.71      1698
     esporte       0.93      0.88      0.90      4663
   ilustrada       0.14      0.89      0.24       131
     mercado       0.84      0.79      0.82      5867
       mundo       0.75      0.84      0.79      2051

    accuracy                           0.80     20513
   macro avg       0.69      0.82      0.71     20513
weighted avg       0.82      0.80      0.81     20513

In [ ]:
import pickle

with open("/content/drive/My Drive/curso_word2vec/rl_cbow.pkl", "wb") as f:
    pickle.dump(RL_cbow, f)

In [ ]:
with open("/content/drive/My Drive/curso_word2vec/rl_sg.pkl", "wb") as f:
    pickle.dump(RL_sg, f)